-- ================================================================
-- MIGRATION : Séparation de reponses_utilisateurs en deux tables
-- - reponses_utilisateurs_francais : mêmes colonnes que reponses_utilisateurs
-- - reponses_utilisateurs_math     : mêmes colonnes + note_calcul, note_methode
--   (note_orthographe retirée, sans objet en maths ; note_ecriture conservée)
-- ================================================================

BEGIN;

CREATE TABLE reponses_utilisateurs_francais (
  id                     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at             timestamptz NOT NULL DEFAULT now(),
  user_id                text,
  session_id             text,
  classe                 text,
  thematique             text,
  sous_categorie         text,
  objectif               text,
  question               text,
  reponse                text,
  tentative              smallint,
  note_ecriture          smallint,
  note_orthographe       smallint,
  note_crpe              smallint,
  note_globale           real,
  texte_support          text,
  reponse_ideale         text,
  id_question_completee  bigint REFERENCES questions_generees(id),
  conseils               text
);

CREATE TABLE reponses_utilisateurs_math (
  id                     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at             timestamptz NOT NULL DEFAULT now(),
  user_id                text,
  session_id             text,
  classe                 text,
  thematique             text,
  sous_categorie         text,
  objectif               text,
  question               text,
  reponse                text,
  tentative              smallint,
  note_ecriture          smallint,
  note_calcul            smallint,
  note_methode           smallint,
  note_crpe              smallint,
  note_globale           real,
  texte_support          text,
  reponse_ideale         text,
  id_question_completee  bigint REFERENCES questions_generees(id),
  conseils               text
);

CREATE INDEX idx_reponses_utilisateurs_francais_user_id ON reponses_utilisateurs_francais(user_id);
CREATE INDEX idx_reponses_utilisateurs_math_user_id      ON reponses_utilisateurs_math(user_id);

-- Répliquer exactement les policies RLS de reponses_utilisateurs
-- (ru_insert / ru_select / ru_update, PERMISSIVE, rôle public, sans
-- restriction) pour ne pas casser l'accès de l'app avec la clé anon.
ALTER TABLE reponses_utilisateurs_francais ENABLE ROW LEVEL SECURITY;
CREATE POLICY ru_francais_insert ON reponses_utilisateurs_francais FOR INSERT TO public WITH CHECK (true);
CREATE POLICY ru_francais_select ON reponses_utilisateurs_francais FOR SELECT TO public USING (true);
CREATE POLICY ru_francais_update ON reponses_utilisateurs_francais FOR UPDATE TO public USING (true) WITH CHECK (true);

ALTER TABLE reponses_utilisateurs_math ENABLE ROW LEVEL SECURITY;
CREATE POLICY ru_math_insert ON reponses_utilisateurs_math FOR INSERT TO public WITH CHECK (true);
CREATE POLICY ru_math_select ON reponses_utilisateurs_math FOR SELECT TO public USING (true);
CREATE POLICY ru_math_update ON reponses_utilisateurs_math FOR UPDATE TO public USING (true) WITH CHECK (true);

COMMIT;
